import { grayscale, lighten, darken } from "polished"


const lightMode = {
  black: "#000",
  white: "#fff",
  text: "#000",
  background: "#fff",
  primary: "#07c",
  secondary: "#609",
  accent: "#90c",
}


const darkMode = {
  black: '#000',
  white: '#fff',
  text: '#fff',
  background: '#222',
  primary: '#0cf',
  secondary: '#90c',
  accent: '#609',
}

const  purpleMode =  {
  black: "#000",
  white: "#fff",
  text: "#fff",
  background: "#90c",
  primary: "#0cf",
  secondary: "#222",
  accent: "#609",
}

const blueMode ={
  black: "#000",
  white: "#fff",
  text: "#fff",
  background: "#0cf",
  primary: "#90c",
  secondary: "#222",
  accent: "#609",
}

const gmcMode =  {
  black: "#000",
  white: "#fff",
  text: "#fff",
  background: "#666",
  primary: "#001C6D",
  secondary: "#1D6D00",
  accent: "#6D001D",
}


export default {
  colors: {
    black: lightMode.black,
    white: lightMode.white,
    text: lightMode.text,
    background: lightMode.background,
    primary: lightMode.primary,
    secondary: lightMode.secondary,
    accent: lightMode.accent,
    primaries: [
      lighten(0.4, lightMode.primary),
      lighten(0.3, lightMode.primary),
      lighten(0.2, lightMode.primary),
      lighten(0.1, lightMode.primary),
      lightMode.primary,
      darken(0.1, lightMode.primary),
      darken(0.2, lightMode.primary),
      darken(0.3, lightMode.primary),
      darken(0.4, lightMode.primary),
    ],
    secondaries:[
      lighten(0.4, lightMode.secondary),
      lighten(0.3, lightMode.secondary),
      lighten(0.2, lightMode.secondary),
      lighten(0.1, lightMode.secondary),
      lightMode.secondary,
      darken(0.1, lightMode.secondary),
      darken(0.2, lightMode.secondary),
      darken(0.3, lightMode.secondary),
      darken(0.4, lightMode.secondary),
    ],
    accents: [
      lighten(0.4, lightMode.accent),
      lighten(0.3, lightMode.accent),
      lighten(0.2, lightMode.accent),
      lighten(0.1, lightMode.accent),
      lightMode.accent,
      darken(0.1, lightMode.accent),
      darken(0.2, lightMode.accent),
      darken(0.3, lightMode.accent),
      darken(0.4, lightMode.accent),
    ],
    grays: [
      grayscale(lighten(0.4, lightMode.black)),
      grayscale(lighten(0.3, lightMode.black)),
      grayscale(lighten(0.2, lightMode.black)),
      grayscale(lighten(0.1, lightMode.black)),
      grayscale(lightMode.black),
      grayscale(darken(0.1, lightMode.black)),
      grayscale(darken(0.2, lightMode.black)),
      grayscale(darken(0.3, lightMode.black)),
      grayscale(darken(0.4, lightMode.black)),
    ],
    modes: {
      gmc: {
        black: gmcMode.black,
        white: gmcMode.white,
        text: gmcMode.text,
        background: gmcMode.background,
        primary: gmcMode.primary,
        secondary: gmcMode.secondary,
        accent: gmcMode.accent,
        primaries: [
          lighten(0.4, gmcMode.primary),
          lighten(0.3, gmcMode.primary),
          lighten(0.2, gmcMode.primary),
          lighten(0.1, gmcMode.primary),
          gmcMode.primary,
          darken(0.1, gmcMode.primary),
          darken(0.2, gmcMode.primary),
          darken(0.3, gmcMode.primary),
          darken(0.4, gmcMode.primary),
        ],
        secondaries:[
          lighten(0.4, gmcMode.secondary),
          lighten(0.3, gmcMode.secondary),
          lighten(0.2, gmcMode.secondary),
          lighten(0.1, gmcMode.secondary),
          gmcMode.secondary,
          darken(0.1, gmcMode.secondary),
          darken(0.2, gmcMode.secondary),
          darken(0.3, gmcMode.secondary),
          darken(0.4, gmcMode.secondary),
        ],
        accents: [
          lighten(0.4, gmcMode.accent),
          lighten(0.3, gmcMode.accent),
          lighten(0.2, gmcMode.accent),
          lighten(0.1, gmcMode.accent),
          gmcMode.accent,
          darken(0.1, gmcMode.accent),
          darken(0.2, gmcMode.accent),
          darken(0.3, gmcMode.accent),
          darken(0.4, gmcMode.accent),
        ],
        grays: [
          grayscale(lighten(0.4, gmcMode.black)),
          grayscale(lighten(0.3, gmcMode.black)),
          grayscale(lighten(0.2, gmcMode.black)),
          grayscale(lighten(0.1, gmcMode.black)),
          grayscale(gmcMode.black),
          grayscale(darken(0.1, gmcMode.black)),
          grayscale(darken(0.2, gmcMode.black)),
          grayscale(darken(0.3, gmcMode.black)),
          grayscale(darken(0.4, gmcMode.black)),
        ],
      },
      dark: {
        black: darkMode.black,
        white: darkMode.white,
        text: darkMode.text,
        background: darkMode.background,
        primary: darkMode.primary,
        secondary: darkMode.secondary,
        accent: darkMode.accent,
        primaries: [
          lighten(0.4, darkMode.primary),
          lighten(0.3, darkMode.primary),
          lighten(0.2, darkMode.primary),
          lighten(0.1, darkMode.primary),
          darkMode.primary,
          darken(0.1, darkMode.primary),
          darken(0.2, darkMode.primary),
          darken(0.3, darkMode.primary),
          darken(0.4, darkMode.primary),
        ],
        secondaries:[
          lighten(0.4, darkMode.secondary),
          lighten(0.3, darkMode.secondary),
          lighten(0.2, darkMode.secondary),
          lighten(0.1, darkMode.secondary),
          darkMode.secondary,
          darken(0.1, darkMode.secondary),
          darken(0.2, darkMode.secondary),
          darken(0.3, darkMode.secondary),
          darken(0.4, darkMode.secondary),
        ],
        accents: [
          lighten(0.4, darkMode.accent),
          lighten(0.3, darkMode.accent),
          lighten(0.2, darkMode.accent),
          lighten(0.1, darkMode.accent),
          darkMode.accent,
          darken(0.1, darkMode.accent),
          darken(0.2, darkMode.accent),
          darken(0.3, darkMode.accent),
          darken(0.4, darkMode.accent),
        ],
        grays: [
          grayscale(lighten(0.4, darkMode.black)),
          grayscale(lighten(0.3, darkMode.black)),
          grayscale(lighten(0.2, darkMode.black)),
          grayscale(lighten(0.1, darkMode.black)),
          grayscale(darkMode.black),
          grayscale(darken(0.1, darkMode.black)),
          grayscale(darken(0.2, darkMode.black)),
          grayscale(darken(0.3, darkMode.black)),
          grayscale(darken(0.4, darkMode.black)),
        ],
      },
      purple: {
        black: purpleMode.black,
        white: purpleMode.white,
        text: purpleMode.text,
        background: purpleMode.background,
        primary: purpleMode.primary,
        secondary: purpleMode.secondary,
        accent: purpleMode.accent,
        primaries: [
          lighten(0.4, purpleMode.primary),
          lighten(0.3, purpleMode.primary),
          lighten(0.2, purpleMode.primary),
          lighten(0.1, purpleMode.primary),
          purpleMode.primary,
          darken(0.1, purpleMode.primary),
          darken(0.2, purpleMode.primary),
          darken(0.3, purpleMode.primary),
          darken(0.4, purpleMode.primary),
        ],
        secondaries:[
          lighten(0.4, purpleMode.secondary),
          lighten(0.3, purpleMode.secondary),
          lighten(0.2, purpleMode.secondary),
          lighten(0.1, purpleMode.secondary),
          purpleMode.secondary,
          darken(0.1, purpleMode.secondary),
          darken(0.2, purpleMode.secondary),
          darken(0.3, purpleMode.secondary),
          darken(0.4, purpleMode.secondary),
        ],
        accents: [
          lighten(0.4, purpleMode.accent),
          lighten(0.3, purpleMode.accent),
          lighten(0.2, purpleMode.accent),
          lighten(0.1, purpleMode.accent),
          purpleMode.accent,
          darken(0.1, purpleMode.accent),
          darken(0.2, purpleMode.accent),
          darken(0.3, purpleMode.accent),
          darken(0.4, purpleMode.accent),
        ],
        grays: [
          grayscale(lighten(0.4, purpleMode.black)),
          grayscale(lighten(0.3, purpleMode.black)),
          grayscale(lighten(0.2, purpleMode.black)),
          grayscale(lighten(0.1, purpleMode.black)),
          grayscale(purpleMode.black),
          grayscale(darken(0.1, purpleMode.black)),
          grayscale(darken(0.2, purpleMode.black)),
          grayscale(darken(0.3, purpleMode.black)),
          grayscale(darken(0.4, purpleMode.black)),
        ],
      },
      blue: {
        black: blueMode.black,
        white: blueMode.white,
        text: blueMode.text,
        background: blueMode.background,
        primary: blueMode.primary,
        secondary: blueMode.secondary,
        accent: blueMode.accent,
        primaries: [
          lighten(0.4, blueMode.primary),
          lighten(0.3, blueMode.primary),
          lighten(0.2, blueMode.primary),
          lighten(0.1, blueMode.primary),
          blueMode.primary,
          darken(0.1, blueMode.primary),
          darken(0.2, blueMode.primary),
          darken(0.3, blueMode.primary),
          darken(0.4, blueMode.primary),
        ],
        secondaries:[
          lighten(0.4, blueMode.secondary),
          lighten(0.3, blueMode.secondary),
          lighten(0.2, blueMode.secondary),
          lighten(0.1, blueMode.secondary),
          blueMode.secondary,
          darken(0.1, blueMode.secondary),
          darken(0.2, blueMode.secondary),
          darken(0.3, blueMode.secondary),
          darken(0.4, blueMode.secondary),
        ],
        accents: [
          lighten(0.4, blueMode.accent),
          lighten(0.3, blueMode.accent),
          lighten(0.2, blueMode.accent),
          lighten(0.1, blueMode.accent),
          blueMode.accent,
          darken(0.1, blueMode.accent),
          darken(0.2, blueMode.accent),
          darken(0.3, blueMode.accent),
          darken(0.4, blueMode.accent),
        ],
        grays: [
          grayscale(lighten(0.4, blueMode.black)),
          grayscale(lighten(0.3, blueMode.black)),
          grayscale(lighten(0.2, blueMode.black)),
          grayscale(lighten(0.1, blueMode.black)),
          grayscale(blueMode.black),
          grayscale(darken(0.1, blueMode.black)),
          grayscale(darken(0.2, blueMode.black)),
          grayscale(darken(0.3, blueMode.black)),
          grayscale(darken(0.4, blueMode.black)),
        ],
      }
    }
  },
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'inherit',
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      color: 'text',
      bg: 'background',
    },
    a: {
      color: 'primary',
      textDecoration: 'none',
      ':hover': {
        color: 'secondary',
        textDecoration: 'underline',
      }
    }
  }
}
